# docker-compose.yml
version: "3.9"

services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    command:
      - "--configFile=/traefik.yml"
      - "--docker.apiVersion=1.40"   # forces Traefik to use API 1.40
    environment:
      - DOCKER_API_VERSION=1.40      # optional but harmless
    ports:
      - "80:80"          # HTTP entrypoint
      - "443:443"        # HTTPS entrypoint (keep for later TLS)
      - "8083:8080"      # Dashboard moved to host port 8083
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - infra-net


networks:
  infra-net:
    external: true