services:
  trilium:
    image: triliumnext/trilium:latest
    container_name: trilium
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ${TRILIUM_DATA_DIR}:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - infra-net

networks:
  infra-net:
    external: true
