services:
  trilium:
    image: triliumnext/trilium:v0.106.0@sha256:be93e82699b12950ac4e2e7b565ce092fe215b8dd6ddfc47921e37b49e6a0e8b
    container_name: trilium
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - TRILIUM_SECURITY_BACKEND_SCRIPTING_ENABLED=true
      - TRILIUM_SECURITY_SQL_CONSOLE_ENABLED=true
    volumes:
      - ${TRILIUM_DATA_DIR}:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - infra-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trilium.rule=Host(`trilium.test`)"
      - "traefik.http.routers.trilium.entrypoints=web"
      - "traefik.http.services.trilium.loadbalancer.server.port=8080"

networks:
  infra-net:
    external: true
